InsightsClub/InsightsClubWebsite

BACKEND/app.js
BACKEND/config/config.env
BACKEND/controllers/authController.js
BACKEND/models/userModel.js
BACKEND/package-lock.json
BACKEND/package.json
BACKEND/routes/index.js

Basic authentication completed !
- User can sign up, verify email, login, logout, change password if it has been forgotten.
- Added User schema.
- Removed body parser and using builtin express methods.

[feat]basic user auth[change]minor tweaks

---

BACKEND/controllers/authController.js
BACKEND/middlewares/verifyUser.js

Issue was detected when the user sent no cookies at all.
req.cookies is an object with null prototype due to which it does not have any of the common JS object functions.
Solution: Added a check - if the req.cookies contains keys or not.

[changes]fixed error req.cookies.hasOwnProperty

---

BACKEND/controllers/authController.js
BACKEND/controllers/blogController.js
BACKEND/controllers/eventsController.js
BACKEND/controllers/managementController.js
BACKEND/middlewares/verifyUser.js
BACKEND/models/blogModel.js
BACKEND/models/userModel.js
BACKEND/package-lock.json
BACKEND/routes/index.js

- minor changes in managementController
- added routes
- TODO: Blog routes and logic

 Added Blog controllers

---

BACKEND/controllers/authController.js
BACKEND/controllers/blogController.js
BACKEND/models/blogModel.js
BACKEND/routes/index.js

- TODO: add image support to Blogs
- Changes: routes structure for 'get all events' and 'get all blogs'. Blog schema now contains contains review fields.

Basic Blog logic completed

---

BACKEND/controllers/authController.js
BACKEND/routes/index.js
FRONTEND/src/components/AuthCards/Auth.jsx
FRONTEND/src/components/AuthCards/auth.css
FRONTEND/src/components/Landing/landing-intro/Intro.jsx
FRONTEND/src/components/Landing/landing-intro/intro.css
FRONTEND/src/components/Navbar/Navbar.css
FRONTEND/src/components/Navbar/Navbar.jsx

- Signin/Sign up UI ready
- [TODO]Invalid input fields need to show error messages (I have included a red underline for invalid inputs in UI as of now)
- [changes]Login route now uses HTTP POST

Signin/up UI ready

---

FRONTEND/src/components/Footer/footer.css
FRONTEND/src/components/Landing/landing-domains/Domains.jsx
FRONTEND/src/components/Landing/landing-domains/domains.css
FRONTEND/src/components/Landing/landing-events/Event-Slides.jsx
FRONTEND/src/components/Landing/landing-events/eventcard.css

- Fixed UI bugs
- [TODO] Update UI based on cookies fetched from auth api
- [TODO] Invalid input fields need to show error messages (I have included a red underline for invalid inputs in UI as of now)

Added card hover effects

---

FRONTEND/src/components/Articles/DetailedArticles/DetailedArticle.css
FRONTEND/src/components/Articles/DetailedArticles/DetailedArticle.jsx
FRONTEND/src/pages/EventsPage/eventsPage.jsx

view article page and detailed article pages are added

Article pages added

---

FRONTEND/src/components/Landing/landing-domains/DomainModal/DomainModal.jsx
FRONTEND/src/components/Landing/landing-domains/DomainModal/domainModal.css
FRONTEND/src/components/Landing/landing-domains/Domains.jsx
FRONTEND/src/components/Landing/landing-domains/domains.css
FRONTEND/src/components/Landing/landing-events/eventcard.css
FRONTEND/src/components/Landing/landing-intro/Intro.jsx
FRONTEND/src/components/Landing/landing-intro/intro.css
FRONTEND/src/components/Navbar/Navbar.jsx

[CHANGES]
- Fixed: Body will not scroll when modals are open.
- Fixed: text-shadow looked horrible in chrome.
[side-effect] headings will look thinner on Firefox etc.
[TODO]
Fetch Insights core members and use them instead of dummy data in Domain modal.

Added domain modal (with dummy data)

---

BACKEND/controllers/authController.js
BACKEND/controllers/managementController.js
BACKEND/models/departmentsModel.js
BACKEND/models/userModel.js
BACKEND/routes/index.js
FRONTEND/src/components/AuthCards/Auth.jsx
FRONTEND/src/components/AuthCards/auth.css
FRONTEND/src/components/Landing/landing-domains/DomainModal/DomainModal.jsx
FRONTEND/src/components/Landing/landing-domains/Domains.jsx

[CHANGES]
- Added departments schema.
- Set up routes for department CRUD.
- Styles changed to adjust for a new feild (department id)
[TODO]
- Users can add their description from the profile section
(YET TO BE DEVELOPED)

Users can now have departments

---

FRONTEND/package-lock.json
FRONTEND/src/App.js
FRONTEND/src/actions/blogs.js
FRONTEND/src/components/Blogs/Blog/Blog.jsx
FRONTEND/src/components/Blogs/CreateBlog/View.jsx
FRONTEND/src/constants/blogsActionTypes.js
FRONTEND/src/reducers/blogs.js

blogs updates

---

.vscode/settings.json
FRONTEND/package.json
FRONTEND/src/components/Blogs/Blog/Blog.jsx
FRONTEND/src/components/Blogs/BlogSiderbar/BlogsSideBar.css
FRONTEND/src/components/Blogs/Blogs.css
FRONTEND/src/components/Blogs/Blogs.jsx

Responsive design fixes of blogs home page

mobile ui fixes

---

BACKEND/app.js
FRONTEND/package-lock.json
FRONTEND/src/components/AboutPage/About.jsx
FRONTEND/src/components/AboutPage/about.css
FRONTEND/src/components/AuthCards/Auth.jsx
FRONTEND/src/components/Blogs/Blog/Blog.jsx
FRONTEND/src/components/Blogs/CreateBlog/View.jsx
FRONTEND/src/components/Landing/landing-domains/DomainModal/DomainModal.jsx
FRONTEND/src/components/Landing/landing-events/Event-Slides.jsx
FRONTEND/src/components/Profile/Blogs/Blogs.jsx

- Changed localhost:8080 links to production server in frontend
- Fixed errors in Aditya's push

Fixed About page UI

---

FRONTEND/src/components/Landing/landing-events/Event-Slides.jsx

- only the needed slide will be active now

Fixed event slider

---

BACKEND/models/blogModel.js
FRONTEND/src/components/Blogs/Blog/Blog.jsx
FRONTEND/src/components/Blogs/CreateBlog/View.css
FRONTEND/src/components/Blogs/CreateBlog/View.jsx

blog fixes

---

BACKEND/controllers/authController.js
FRONTEND/src/actions/article.js
FRONTEND/src/actions/blogs.js
FRONTEND/src/actions/events.js
FRONTEND/src/components/AuthCards/Auth.jsx
FRONTEND/src/components/Blogs/Blog/Blog.jsx
FRONTEND/src/components/Blogs/CreateBlog/View.jsx
FRONTEND/src/components/Landing/landing-domains/DomainModal/DomainModal.jsx
FRONTEND/src/components/Landing/landing-domains/Domains.jsx
FRONTEND/src/components/Landing/landing-events/Event-Slides.jsx
FRONTEND/src/components/Profile/Blogs/Blogs.jsx
FRONTEND/src/components/VideoPage/Video.jsx

- All links now point to new domain

Links changed

---

BACKEND/controllers/blogController.js
FRONTEND/src/components/Blogs/Blog/Blog.jsx
FRONTEND/src/components/Blogs/Blogs.jsx
FRONTEND/src/components/Blogs/CreateBlog/View.jsx

Blog API fixes

---

BACKEND/controllers/videoController.js
BACKEND/models/videoModel.js
FRONTEND/src/App.js
FRONTEND/src/components/VideoPage/NewVideo.jsx
FRONTEND/src/components/VideoPage/Video.jsx
FRONTEND/src/components/VideoPage/newVideo.css

- backend configured to upload video thumbs to cloudinary (this is not tested)
TODO:
- protect create video route (only admins should access it)
- button or link to navigate to create video page

[untested] "Create video" page added

---

BACKEND/controllers/videoController.js
FRONTEND/src/App.js
FRONTEND/src/components/VideoPage/NewVideo.jsx
FRONTEND/src/pages/Profile/Profile.jsx
FRONTEND/src/utils/ProtectedRoute.jsx

- added logic for admins + coadmins level access
- access modes - coadmin level acess, admins only, none
[CHANGES]
- profile page now has a navbar and a footer

Protected route logic and minor changes

---

FRONTEND/src/components/Blogs/Blogs.jsx
FRONTEND/src/components/Profile/Blogs/Blog.css
FRONTEND/src/components/Profile/Blogs/Blogs.jsx

Minor fixes and changes on blog page

minor changes on blog page

---

FRONTEND/src/components/Blogs/Blog/Blog.css
FRONTEND/src/components/Blogs/Blog/Blog.jsx
FRONTEND/src/components/Blogs/Blogs.css
FRONTEND/src/components/Blogs/Blogs.jsx

Blog can be sorted based on likes and time of upload

blog sorting feature added

---

FRONTEND/src/components/VideoPage/Video.jsx
FRONTEND/src/components/VideoPage/video.css

- added link to visit videos/new route on frontend
- only admins and coadmins can access this
- this page was already made but the button to access it is added

Users can now add videos as embeds

---

BACKEND/controllers/videoController.js
FRONTEND/src/components/VideoPage/NewVideo.jsx
FRONTEND/src/components/VideoPage/newVideo.css

- added a label to explain file input in videos/new
- added checks in backend to not store invalid or empty form data

handles invalid input in add video form

---

FRONTEND/src/components/Blogs/Blogs.css
FRONTEND/src/components/Blogs/Blogs.jsx
FRONTEND/src/components/Blogs/CreateBlog/View.css
FRONTEND/src/components/Blogs/CreateBlog/View.jsx

UI Fixes
Like Button Fixes
Sort blog bug fixed

blog page fixes

---

FRONTEND/src/components/Blogs/Blog/Blog.jsx
FRONTEND/src/components/Blogs/BlogsNavbar/BlogsNavbar.css
FRONTEND/src/components/Blogs/BlogsNavbar/BlogsNavbar.jsx
FRONTEND/src/components/Blogs/CreateBlog/View.jsx

blog minor fixes 💀

---

BACKEND/controllers/authController.js

- Error occurred because Oauth2 refresh token kept expiring after 7 days since the Email API is in testing mode
- We have no plans of publishing it and submitting all the required things along with it
- Hence we need to keep updating refresh tokens weekly
- However, due to this error now the server will not crash as the Promise rejection has been handled

Handled 'Invalid Grant' error

---

BACKEND/controllers/authController.js

- Error occurred because Oauth2 refresh token kept expiring after 7 days since the Email API is in testing mode
- We have no plans of publishing it and submitting all the required things along with it
- Hence we need to keep updating refresh tokens weekly
- However, due to this error now the server will not crash as the Promise rejection has been handled

added checks for expired refresh token
